default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bookhouse_development

test:
  <<: *default
  database: bookhouse_test

production:
  <<: *default
  database: bookhouse_production
  host: localhost
  username: bookhouse
  password: bookhouse
