default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: free_parking_development

test:
  <<: *default
  database: free_parking_test

production:
  <<: *default
  database: free_parking_production
  host: localhost
  username: ENV['prod_username']
  password: ENV['prod_pwd']
